services:
  db:
    image: postgres:15
    restart: always
    container_name: product_pg
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: price_aggregator
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: product_redis
    ports:
      - '6379:6379'

volumes:
  pgdata: